language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

install: echo "skip 'gradle assemble' step"

script: gradle build -x restdoc --continue

after_success:
 - ./gradlew cobertura coveralls
 
